export const expressionLabels: Record<string, string> = {
  admiration: "Admiration",
  adoration: "Adoration",
  aestheticAppreciation: "Aesthetic Appreciation",
  amusement: "Amusement",
  anger: "Anger",
  annoyance: "Annoyance",
  anxiety: "Anxiety",
  awe: "Awe",
  awkwardness: "Awkwardness",
  boredom: "Boredom",
  calmness: "Calmness",
  concentration: "Concentration",
  contemplation: "Contemplation",
  confusion: "Confusion",
  contempt: "Contempt",
  contentment: "Contentment",
  craving: "Craving",
  determination: "Determination",
  disappointment: "Disappointment",
  disapproval: "Disapproval",
  disgust: "Disgust",
  distress: "Distress",
  doubt: "Doubt",
  ecstasy: "Ecstasy",
  embarrassment: "Embarrassment",
  empathicPain: "Empathic Pain",
  enthusiasm: "Enthusiasm",
  entrancement: "Entrancement",
  envy: "Envy",
  excitement: "Excitement",
  fear: "Fear",
  gratitude: "Gratitude",
  guilt: "Guilt",
  horror: "Horror",
  interest: "Interest",
  joy: "Joy",
  love: "Love",
  neutral: "Neutral",
  nostalgia: "Nostalgia",
  pain: "Pain",
  pride: "Pride",
  realization: "Realization",
  relief: "Relief",
  romance: "Romance",
  sadness: "Sadness",
  sarcasm: "Sarcasm",
  satisfaction: "Satisfaction",
  sexualDesire: "Sexual Desire",
  shame: "Shame",
  surprise: "Surprise",
  surpriseNegative: "Surprise (Negative)",
  surprisePositive: "Surprise (Positive)",
  sympathy: "Sympathy",
  tiredness: "Tiredness",
  triumph: "Triumph",
};

export const expressionColors = {
  admiration: "#ffc58f",
  adoration: "#ffc6cc",
  aestheticAppreciation: "#e2cbff",
  amusement: "#febf52",
  anger: "#b21816",
  annoyance: "#5f6b7c",
  anxiety: "#6e42cc",
  awe: "#7dabd3",
  awkwardness: "#d7d99d",
  boredom: "#8f99a6",
  calmness: "#a9cce1",
  concentration: "#336cff",
  contemplation: "#b0aeef",
  confusion: "#c66a26",
  contempt: "#76842d",
  contentment: "#e5c6b4",
  craving: "#54591c",
  determination: "#ff5c00",
  disappointment: "#006c7c",
  disapproval: "#4e591a",
  disgust: "#1a7a41",
  distress: "#c5f264",
  doubt: "#998644",
  ecstasy: "#ff48a4",
  embarrassment: "#63c653",
  empathicPain: "#ca5555",
  enthusiasm: "#ff9142",
  entrancement: "#7554d6",
  envy: "#1d4921",
  excitement: "#fff974",
  fear: "#d1c9ef",
  gratitude: "#f0d3b6",
  guilt: "#879aa1",
  horror: "#772e7a",
  interest: "#8fd1c4",
  joy: "#ffd600",
  love: "#f44f4c",
  neutral: "#879aa1",
  nostalgia: "#b087a1",
  pain: "#8c1d1d",
  pride: "#9a4cb6",
  realization: "#217aa8",
  relief: "#fe927a",
  romance: "#f0cc86",
  sadness: "#305575",
  sarcasm: "#7f53a4",
  satisfaction: "#a6ddaf",
  sexualDesire: "#aa0d59",
  shame: "#8a6262",
  surprise: "#70e63a",
  surpriseNegative: "#319d3f",
  surprisePositive: "#7affff",
  sympathy: "#7f88e0",
  tiredness: "#757575",
  triumph: "#ec8132",
} as const;

export const isExpressionColor = (
  color: string
): color is keyof typeof expressionColors => {
  return color in expressionColors;
};

export type ExpressionKey = keyof typeof expressionColors;